### ISSUE TITLE
Update the animation property in SwiftUI 3 (Xcode 13)

### ISSUE THREAD

**Issue by rsyncOSX** [elai950/AlertToast#10]
**Describe the bug**

'animation' was deprecated in macOS 12.0: Use withAnimation or animation(_:value:) instead.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by elai950** [comment]
Fixed in version 1.3.0
Closing issue.

**Comment by rsyncOSX** [comment]
Great work, thx..
