### ISSUE TITLE
Toast hides behind the Navigation view

### ISSUE THREAD

**Issue by marvadia** [elai950/AlertToast#13]
**Describe the bug**
When presenting AlertToast in SwiftUI view with Inline Navigation view, AlertToast with display mode (.hud) hides behind the navigation view. 

**To Reproduce**
```
import SwiftUI
import AlertToast

struct ContentView: View {
    @State var isPresenting = true
    var body: some View {
        NavigationView {
        ZStack {
            VStack{
                Text("Hello, world!")
                    .padding()
            }
            .frame(maxWidth: .infinity, maxHeight: .infinity)
            .toast(isPresenting: $isPresenting, duration: 2.0, tapToDismiss: true, alert: {
                
                return AlertToast(displayMode: .hud, type: .complete(.white), title: "Testing Alert Toast")
            })
        }
        .navigationTitle("Navigation Title")
        .navigationBarTitleDisplayMode(.inline)
        }
    }
}
```

**Expected behavior**
AlertToast should present in front of the navigation view. 

**Screenshots**
![IMG_5045](https://user-images.githubusercontent.com/1870639/128079163-3338b5cb-5b98-4499-b3fb-c5a81d7786b5.PNG)

**Smartphone (please complete the following information):**
 - Device: iPhone12 Mini
 - OS: iOS14.6

**Comment by elai950** [comment]
Hi @marvadia,
Please move the `.toast` modifier to be implemented in `NavigationView`.
This would solve your problem.

At this point, the view hierarchy in SwiftUI doesn't let you modify this option without putting the view modifier in the right place. You're placing a view below the navigation bar and the highest view in your hierarchy is `NavigationView` so of course, the `AlertToast` view would be below that.

I really advise you to check the article I've written about AlertToast and check the Bonus section.

Closing issue.
