### ISSUE TITLE
Invalid frame dimension (negative or non-finite).

### ISSUE THREAD

**Issue by solidHeroLink** [elai950/AlertToast#18]
Getting this error message in Xcode 13.

Invalid frame dimension (negative or non-finite).

It's happening on this line

`.frame(maxWidth: .infinity, maxHeight: alert().displayMode == .alert ? .infinity : -hostRect.midY / 2, alignment: .center)`

**Comment by elai950** [comment]
Fixed.
Please use the updated package.
