### ISSUE TITLE
Menu style wanted

### ISSUE THREAD

**Issue by xiaoxidong** [elai950/AlertToast#2]
The swiftUI default Menu style is very restrict, it is hard to custom the content style. And I find that all the open source toast don't have it. 
I am a product manager learning swiftUI, so is it possible to add custom view for menu like style, and click the button shows the content view.
My thinking is pass the location of the clicked button and show the toast with the location in the toast?
Thank you so much.

**Comment by elai950** [comment]
Can you please show an example of what you meant?  I didn't understand if you asking about a menu or a toast.

**Comment by xiaoxidong** [comment]
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-02-24 at 11 01 22](https://user-images.githubusercontent.com/3838258/108941256-b8eef100-768f-11eb-81ae-4dd173b9e97c.png)
It is a menu style, the buttons can not custom, and use Zstack to show the content is really annoying, and I am wondering is it possible to use the toast method to show the content in a specific location based on the clicked element, and show the content above or below based on the location?

**Comment by elai950** [comment]
Sorry but this repo is about Alerts and Toasts not about menus.
What you asking is a different situation and implementation, not something that AlertToast can be related to.
Closing the issue for those reasons.
