### ISSUE TITLE
'AlertToast' initializer is inaccessible due to 'internal' protection level

### ISSUE THREAD

**Issue by solidHeroLink** [elai950/AlertToast#20]
Updated to version 1.3.5 and still seeing this error message in Xcode 13.

`'AlertToast' initializer is inaccessible due to 'internal' protection level`

```
.toast(isPresenting: $showToast){
            
            AlertToast(displayMode: .hud, type: .systemImage(toastImage!, toastImageColor!), title: toastTitle, subTitle: toastSubTitle)
                
        }
```

**Comment by afern247** [comment]
Same problem, upgrading from 1.3.0 -> 1.3.5 cause that issue to appear and breaks the app. So cannot upgrade.

**Comment by elai950** [comment]
Updated to version 1.3.7
Please let me know if the problem still exists
