### ISSUE TITLE
SwiftUI issue "Invalid frame dimension (negative or non-finite).

### ISSUE THREAD

**Issue by toqix** [elai950/AlertToast#21]
**Describe the bug**
Xcode shows an issue when certain alerts are displayed

**Screenshots**

<img width="1755" alt="Screenshot" src="https://user-images.githubusercontent.com/64910316/134350960-acf4f7ad-33f9-4a0c-b6f8-79393e4d0056.png">

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iPhone 11
 - OS: [e.g. iOS8.1] iOS15.0

**Additional context**
Problem occurs in AlertToast/AlertToast/line 439

.

**Comment by elai950** [comment]
This problem was fixed already in release 3.5.0.
Please update your pod / SPM.
