### ISSUE TITLE
Blur Background

### ISSUE THREAD

**Issue by blockiyt** [elai950/AlertToast#22]
**Is your feature request related to a problem? Please describe.**

I would very like to have an blurred background

**Describe the solution you'd like**

When displayMode is set to .hud, the background of the complete view should be blurred

**Describe alternatives you've considered**

Making a manual blur

**Additional context**

-

**Comment by elai950** [comment]
These are the default settings already.
Please check the source code and see that the background for the hud is BlurView.

Closed.
