### ISSUE TITLE
Alert Toast (.hud display mode) is displayed behind the navigation bar items

### ISSUE THREAD

**Issue by Matttx** [elai950/AlertToast#30]
**Describe the bug**
If there is a navigation bar item that has a long text, the .alert toast will be displayed behind it

**To Reproduce**
1. Create a view with a NavigationView
2. Add a navigation bar item with a long text to the trailing position (example: Add to favorite)
3. Trigger an .hud AlertToast

**Expected behavior**
The AlertToast should be on top of the navigation bar items

**Screenshots**
![Simulator Screen Shot - iPhone 13 - 2021-11-14 at 14 50 24](https://user-images.githubusercontent.com/46529475/141684025-4eefdf8c-747c-450f-90ad-a0291495c8bd.png)

**Smartphone:**
 - Device: iPhone 13
 - OS: iOS 15
 - Version: 1.3.7

**Comment by Matttx** [comment]
It would be a pleasure to contribute to this issue 😄

**Comment by Matttx** [comment]
I'm closing the issue because I just have to add the .toast to the NavigationView and not inside it

Sorry 😅

**Comment by app-arianamini** [comment]
FYI: you can also set the offsetY in .toast
