### ISSUE TITLE
Toast truncated when it is presented from a sheet

### ISSUE THREAD

**Issue by pradeepb28** [elai950/AlertToast#33]
**Describe the bug**
Toast truncated when it is presented from a sheet when using swiftui
![CleanShot 2021-12-20 at 16 54 39@2x](https://user-images.githubusercontent.com/6823101/146760210-b1be6204-af9f-4777-9a1a-6350c9d596c3.png)

**To Reproduce**
1. Open a screen as a sheet (not full cover)
2. Trigger the toast from a button
3. Top portion of toast is been truncated

**Expected behavior**
Full toast must be visible

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] 15.0

**Smartphone (please complete the following information):**

**Comment by elai950** [comment]
Please use the `offsetY` parameter that can be found in `.toast`.
This will help you fix the issue.

The problem is that currently, in SwiftUI there's no way to put a view at the top of the hierarchy.
