### ISSUE TITLE
Cannot find 'AlertStyle' in scope

### ISSUE THREAD

**Issue by OzmanSolomon** [elai950/AlertToast#35]
whenever I use AlertStyle Xcode throw "Cannot find 'AlertStyle' in scope"
I'm using 1.3.7
I tried to switch to master and decrease the version 
I even tried AlertCustom and not worked 
I checked [this issue](https://github.com/elai950/AlertToast/issues/23) but nothing was helpful for my case

**Comment by mac-gallagher** [comment]
Try `AlertToast.AlertStyle`
