### ISSUE TITLE
Toast can become stuck open if it is re-shown before it completely fades out.

### ISSUE THREAD

**Issue by barnard-b** [elai950/AlertToast#4]
**Describe the bug**
Showing the toast after it starts fading out causes it to become stuck open.

**To Reproduce**
1. Attach the variable used for the toast `isPresented` to a button.
2. Click the button.
3. When the toast starts fading out, click the button again.

**Expected behavior**
The toast fades back in and automatically fades back out at the end of the expected show duration.

**Actual behavior**
The toast fades back in and remains shown until it is manually dismissed by tapping it.

**Screenshots**
![AlertToast-toast-stuck](https://user-images.githubusercontent.com/44757473/109567245-0d8cd480-7ab3-11eb-8462-94c44c6d8f07.gif)

**Additional context**
The issue is caused by the dismiss delay being set in `onAppear`, which is not called unless the view has completely faded out before it fades back in.

I was able to solve the issue in iOS 14/macOS 11 using `onChange(of:)` instead of `onAppear` ([see this commit](https://github.com/barnard-b/AlertToast/commit/b9882b713015d233476cf8851f4126240c825ebf)). However, `onChange(of:)` is not available in iOS 13 so I am not sure this is the solution you would want to use.

**Sample Code**
```
struct ContentView: View {
    
    @State var showToast = false
    
    var body: some View {
        Text("Hello, world!")
            .padding()
            .toast(isPresenting: $showToast) {
                AlertToast(type: .complete(.green))
            }
        
        Spacer()
            .frame(height: 150)
        
        Button(action: { showToast = true }) {
            Text("Press Me!")
        }
        
    }
}
```

**Comment by elai950** [comment]
Thank you for your contribution!
I published a new update with a fix for this problem (version 1.2.2).
Now working for both iOS 13 & 14 with `onChange`.

For this reason I'm closing this issue.
Please reopen in the future if this problem returns.
