### ISSUE TITLE
Background opacity of View when AlertToast type hud

### ISSUE THREAD

**Issue by toseefkhilji** [elai950/AlertToast#42]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I required to set my View should dim background when AlertToast type **hud** presented.

**Describe alternatives you've considered**

**Additional context**
I want to achieve something like below
![Screenshot 2021-02-18 at 11 07 59](https://user-images.githubusercontent.com/2367614/159667593-63e45b10-8b39-4612-8bb0-bb9ac534d573.png)

**Comment by egehankalayci** [comment]
#41 
You can use this repository for this feature. 
[alert-dismiss-mode-and-background ](https://github.com/egehankalayci/AlertToast/tree/alert-dismiss-mode-and-background)

**Comment by elai950** [comment]
Hey @toseefkhilji ,
You can achieve this kind of design when adding the `style` parameter and changing the background color.

```swift
AlertToast(displayMode: .alert, type: .regular, title: "Hello World!", style: .style(backgroundColor: .white))
```
