### ISSUE TITLE
Wrong position of toast while displaying in sheet

### ISSUE THREAD

**Issue by Rminsh** [elai950/AlertToast#5]
**Describe the bug**
Toast will show in wrong position with hud display mode when using it in sheet. This bug appears only in iOS

**To Reproduce**
1. Define a view as sheet
2. Add toast to it with hud display mode
3. Call the toast to show

**Expected behavior**
The Y Position of Toast should be much more below or even below the NavigationView (if is defined)

**Screenshots**
![IMG_0361](https://user-images.githubusercontent.com/4667751/110303261-70c8ba80-800f-11eb-8d84-bab59563cc0d.PNG)

**Smartphone:**
 - Device: iPhone 12
 - OS: iOS 14.4

**Sample code:**
```
import SwiftUI
import AlertToast

struct ContentView: View {
    
    @State private var showingDetail = false
    
    var body: some View {
        Button("Show Detail") {
            showingDetail.toggle()
        }
        .sheet(isPresented: $showingDetail) {
            NextView()
        }
    }
}

struct NextView: View {
    
    @State var showToast = false
    
    var body: some View {
        ScrollView {
            Button("Show Detail") {
                showToast.toggle()
            }
            .padding()
        }.toast(isPresenting: $showToast, duration: 3, tapToDismiss: true, alert: {
            AlertToast(
                displayMode: .hud,
                type: .systemImage("checkmark.circle.fill", .green),
                title: "Test",
                subTitle: "Some message")
            
        })
    }
}
```

**Comment by elai950** [comment]
The `.toast` modifier should always be at the top of all view builders.
Add a view builder (for example VStack) then implement the `.toast` on the vstack after the `.sheet` modifier.
Try this:

```swift
var body: some View {
        VStack{
        Button("Show Detail") {
            showingDetail.toggle()
        }
        }
.sheet(isPresented: $showingDetail) {
            NextView()
        }
//Implement `.toast` here
    }
```

**Comment by Rminsh** [comment]
> The `.toast` modifier should always be at the top of all view builders.
> Add a view builder (for example VStack) then implement the `.toast` on the vstack after the `.sheet` modifier.
> Try this:
> 
> ```swift
> var body: some View {
>         VStack{
>         Button("Show Detail") {
>             showingDetail.toggle()
>         }
>         }
> .sheet(isPresented: $showingDetail) {
>             NextView()
>         }
> //Implement `.toast` here
>     }
> ```

If I implement toast modifier in the Parent View, the toast will show up behind my sheet like this:
<img width="366" alt="Screen Shot 2021-03-08 at 4 00 15 PM" src="https://user-images.githubusercontent.com/4667751/110321920-98c41800-8027-11eb-9ccb-ca0c869044b2.png">
```
import SwiftUI
import AlertToast

struct ContentView: View {
    
    @State var showToast = false
    @State private var showingDetail = false
    
    var body: some View {
        Button("Show Detail") {
            showingDetail.toggle()
        }
        .sheet(isPresented: $showingDetail) {
            childView
        }
        .toast(isPresenting: $showToast, duration: 3, tapToDismiss: true, alert: {
            AlertToast(
                displayMode: .hud,
                type: .systemImage("checkmark.circle.fill", .green),
                title: "Test",
                subTitle: "Some message")
            
        })
    }
    
    var childView: some View {
        ScrollView {
            Button("Show Detail") {
                showToast.toggle()
            }
            .padding()
        }
    }
}
```

So the correct way is to implement toast in the Child view and the Y Position should be based on the current view

**Comment by Rminsh** [comment]
> The `.toast` modifier should always be at the top of all view builders.
> Add a view builder (for example VStack) then implement the `.toast` on the vstack after the `.sheet` modifier.
> Try this:
> 
> ```swift
> var body: some View {
>         VStack{
>         Button("Show Detail") {
>             showingDetail.toggle()
>         }
>         }
> .sheet(isPresented: $showingDetail) {
>             NextView()
>         }
> //Implement `.toast` here
>     }
> ```

If I implement toast modifier in the Parent View, the toast will show up behind my sheet like this:
<img width="366" alt="Screen Shot 2021-03-08 at 4 00 15 PM" src="https://user-images.githubusercontent.com/4667751/110321920-98c41800-8027-11eb-9ccb-ca0c869044b2.png">
```
import SwiftUI
import AlertToast

struct ContentView: View {
    
    @State var showToast = false
    @State private var showingDetail = false
    
    var body: some View {
        Button("Show Detail") {
            showingDetail.toggle()
        }
        .sheet(isPresented: $showingDetail) {
            childView
        }
        .toast(isPresenting: $showToast, duration: 3, tapToDismiss: true, alert: {
            AlertToast(
                displayMode: .hud,
                type: .systemImage("checkmark.circle.fill", .green),
                title: "Test",
                subTitle: "Some message")
            
        })
    }
    
    var childView: some View {
        ScrollView {
            Button("Show Detail") {
                showToast.toggle()
            }
            .padding()
        }
    }
}
```

So the correct way is to implement toast in the Child view and the Y Position should be based on the current view

**Comment by elai950** [comment]
This is actually how AlertToast works. By receiving the Y position if the current view.
Do not put '.toast' on Button, implement it on ViewBuilder, like Group.

**Comment by FaroukZeino** [comment]
> This is actually how AlertToast works. By receiving the Y position in the current view.
> Do not put '.toast' on Button, implement it on ViewBuilder, like Group.
> 
> '.sheet' can be on a button but it's not the same case for AlertToast.

This doesn't solve the problem, I have put the toast above the VStack in a Sheet, but the position still incorrect as @Rminsh showed.

**Comment by iKK001** [comment]
same here, this does not solve the problem (iOS 14.6)

**Comment by elai950** [comment]
I've released a new version where you can manually offset the height until I'll find a better solution.

```swift
.toast(isPresenting: ...., offsetY: CGFloat)
```

Closing issue.
