### ISSUE TITLE
tvOS compatibility possible?

### ISSUE THREAD

**Issue by grill2010** [elai950/AlertToast#51]
**Is your feature request related to a problem? Please describe.**
It's not really a problem but I'm just porting my iOS app to tvOS and I was surprised that this library doesn't work on tvOS. Is there any specific reason for that?

**Describe the solution you'd like**
To be able to use this lib on tvOS apps.

**Describe alternatives you've considered**
Only other solution is to not use AlertToast on tvOS and build the view in a different way.

**Additional context**
I just finished porting my Android app to iOS so some of the Apple stuff is still new to me. If it is obvious why this lib can't work on tvOS I'm sorry for creating this ticket.

**Comment by elai950** [comment]
Hey @grill2010 ,
This is definitely a feature that I would add in the future.
Currently, I don't have enough time to create it so I'll close this issue and reopen it once it becomes more relevant.
