### ISSUE TITLE
Swipe to dismiss toast

### ISSUE THREAD

**Issue by lukepistrol** [elai950/AlertToast#56]
**Is your feature request related to a problem? Please describe.**
At the moment it is only possible to dismiss a toast by tapping on it.

**Describe the solution you'd like**
It would be nice if we could dismiss it by swiping (up|down) depending on where it is located on the screen.

**Comment by elai950** [comment]
Hey @lukepistrol ,
This is definitely a feature that I will add to AlertToast but currently, I don't have enough time to work on that.
I'm closing this issue and reopen it once it becomes more relevant.
