### ISSUE TITLE
If type is .loading, its background parent view is still clickable

### ISSUE THREAD

**Issue by chitgoks** [elai950/AlertToast#57]
How to prevent it and make it modal? At least have it dim the background. or is this a feature request since it is not  available?

**Comment by elai950** [comment]
Hey @chitgoks ,
You can always use the `.disable` view modifier on the parent view and put the binding variable that loading in the parameter.

```swift
VStack{
   /// some view with alert toast view modifier...
}
.disable(isLoading)
```

**Comment by chitgoks** [comment]
Thanks. still a newbie. I didnt know about the .disable modifier.

**Comment by chitgoks** [comment]
@elai950 the .disable works. my other question is how to apply a dimmed background from this
```
.toast(isPresenting: $showProgressToast) {
            AlertToast(type: .loading, subTitle: Optional(StringTool.localize("downloading_tide_details")))
        }
```

i tried it like this
```
ZStack {
                AlertToast(type: .loading, subTitle: Optional("downloading...")))
            }
            .frame(maxWidth: .infinity, maxHeight: .infinity)
            .background(Color.primary.opacity(0.2))
```
But it says Cannot convert value of type 'some View' to closure result type 'AlertToast'

Thoughts?

**Comment by chitgoks** [comment]
@elai950 followup. how can i add a full screen blurred background?

```
.toast(isPresenting: $showProgressToast) {
            VStack {
                AlertToast(type: .loading, subTitle: Optional(StringTool.localize("downloading_city_weather")))
            }
            .frame(maxWidth: .infinity, minHeight: .infinity)
            .background(.black.opacity(0.5))
        }
```

This shows an error. Cannot convert value of type 'some View' to closure result type 'AlertToast'
