### ISSUE TITLE
Issue: Swift Package Manager not working

### ISSUE THREAD

**Issue by HopeOfITInChina** [elai950/AlertToast#7]
when Swift Package Manager install this Package
that keep fetching for all day
other  Package can installed smoothly
just this Package can't
thank you

**Comment by elai950** [comment]
The SPM looks to works well on my side.
Try choosing the branch it might help
![צילום מסך 2021-03-24 ב-10 16 35](https://user-images.githubusercontent.com/37900883/112277242-38211600-8c8a-11eb-8029-c50acf8927dc.png)

**Comment by HopeOfITInChina** [comment]
this keep fetching
![image](https://user-images.githubusercontent.com/81154930/112406766-bc899c80-8d4f-11eb-9d63-73414ca9f435.png)
