### ISSUE TITLE
Toast renders behind Keyboard.

### ISSUE THREAD

**Issue by toqix** [elai950/AlertToast#8]
**Describe the bug**
I'm not sure if that's possible to achieve, but when showing a toast alert while a keyboard is shown the toast renders behind it.

**To Reproduce**
1. Create a SwiftUI View
2. Create a textfield and Button
3. The Button should "activate" a toast alert.
4. Now type something in the textfield and press the button when the keyboard is shown. Here you go...

**Expected behavior**
I'd expect the toast to render in front of the keyboard, still I'm not sure if that's possible to achieve.

**Screenshots**
![image](https://user-images.githubusercontent.com/64910316/113551062-5aa12080-95f4-11eb-8faa-354cfc972b2f.png)

**Desktop (please complete the following information):**
- only on iOS!

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 14.4.2
 

**Additional context**
Still thank you for the nice library.

**Comment by elai950** [comment]
Hi!
The keyboard should always be the top view, it's the system requirement.

I understand that after pressing the `Done` button the toast should present.
If you'd like, you can use this function to dismiss the keyboard before the toast presenting.

Run this function before the `Binding<Bool>` you using to present toast:
```swift
func hideKeyboard() {
    UIApplication.shared.sendAction(#selector(UIResponder.resignFirstResponder), to: nil, from: nil, for: nil)
}
```

**Comment by toqix** [comment]
I mean that makes sense. Thank you for the help 😁.
