### ISSUE TITLE
Privacy Manifest

### ISSUE THREAD

**Issue by cyrillelegrand** [elai950/AlertToast#88]
Hello,

As we approach the upcoming spring and the anticipated implementation of the [Privacy Manifest](https://developer.apple.com/support/third-party-SDK-requirements/) by Apple, it's crucial to ensure that your SDK fully complies with Apple's requirements.

Does your SDK need to include it?
If so, do you have a release date planned?

Thank you in advance for your attention to this matter.

Best regards

**Comment by elai950** [comment]
@cyrillelegrand 

Hi,
Thank you for using this library and I hope it fits you well.

AlertToast isn't listed in the SDKs that requires to include privacy manifest.

I do plan on adding a privacy manifest though in the near future because at some point I'll be required to do so, so why not.

**Comment by cyrillelegrand** [comment]
Hi, 

Apple says on [this page](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests) that "Third-party SDKs need to provide their own privacy manifest files that record the types of data they collect", so I guess that it's a matter of time before all SDKs, whether they're in the big list or no, will be required to declare their (non-)usage.

Seems like [SnapKit already added an empty privacy manifest](https://github.com/SnapKit/SnapKit/blob/4478b2234e85c36b9f2c855d909037dc4dc08eda/Sources/PrivacyInfo.xcprivacy#L5), and we're going to add the same to our private SDKs too, this might be a good starting point.

**Comment by elai950** [comment]
Thanks for your help I'm going to add that to the library as well.
If that's ok with you, I'm closing this issue.
Feel free to reopen this issue when there's a need.
