### ISSUE TITLE
Detecting a tap on the banner

### ISSUE THREAD

**Issue by helloniklas** [elai950/AlertToast#9]
Is there an easy way to detect a tap on the banner in order to take an action if it was tapped or not.

**Comment by elai950** [comment]
You can use the completion handler to take an action:

```swift
.toast(isPresenting: $showAlert, duration: 2, tapToDismiss: true, alert: {
   //AlertToast Goes Here
}, completion: { dismissed in
   //Completion block after dismiss (returns true)
})
```

Hope this answers your question.

**Comment by helloniklas** [comment]
I tried that, but it's always called with true. So I can't differentiate between user tapping on to dismiss, or it just being auto dismissed after 2 seconds. The same complexion handler is called on both occasions.

**Comment by elai950** [comment]
I've now added a new handler `onTap` that you can use.

```swift
.toast(isPresenting: $showAlert, duration: 2, tapToDismiss: true, alert: {
   //AlertToast Goes Here
}, onTap: {
 //On tap would call either `tapToDismiss` is false/true
 //If tapToDismiss is true, this action would call and then dismiss the alert
}, completion: {
   //Completion block after dismiss WITHOUT escaping variables
})
```

Don't forget to set `duration` to 0 if you don't want the alert to be auto dismissed.

**Comment by helloniklas** [comment]
Amazing that’s great. Thanks.
